org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
forge_version=65.1.0
forge_version_range=[65,)

mod_id=offhand_fix
mod_name=Kossman's Offhand Fix
mod_license=MIT
mod_version=0.1.1
mod_group_id=dev.dangeroni.offhandfix
mod_authors=Dangeroni Labs
mod_description=Improves offhand stack handling by refilling compatible stacks before swapping.
mod_repository_url=https://github.com/Dangeroni-Labs/offhand-fix
mod_issues_url=https://github.com/Dangeroni-Labs/offhand-fix/issues
