org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.67

mod_id=offhand_fix
mod_name=Kossman's Offhand Fix
mod_license=MIT
mod_version=0.1.0
mod_group_id=dev.dangeroni.offhandfix
mod_authors=Dangeroni Labs
mod_description=Improves offhand stack handling by refilling compatible stacks during shift-click and swap-hand interactions.
mod_repository_url=https://github.com/Dangeroni-Labs/offhand-fix
mod_issues_url=https://github.com/Dangeroni-Labs/offhand-fix/issues
