# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.caching=true
net.minecraftforge.gradle.merge-source-sets=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=0.1.1
group=dev.dangeroni.offhandfix

# Dependencies
fabric_api_version=0.158.0+26.2

minecraft_version_range=[26.2,26.3)
forge_version=65.1.0
forge_version_range=[65,)

mod_id=offhand_fix
mod_name=Kossman's Offhand Fix
mod_license=MIT
mod_version=0.1.1
mod_group_id=dev.dangeroni.offhandfix
mod_authors=Dangeroni Labs
mod_description=Improves offhand stack handling by refilling compatible stacks before swapping.
mod_repository_url=https://github.com/Dangeroni-Labs/offhand-fix
mod_issues_url=https://github.com/Dangeroni-Labs/offhand-fix/issues

neo_version=26.2.0.67
